name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: '2.7.6'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version:  ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake
